### ISSUE TITLE
Unable to serve the ui in stage (production)

### ISSUE THREAD

**Issue by almothafar** [mmizutani/sbt-play-gulp#10]
Simply when I run the activator in development mode, its ok, but when I try to run in stage, i just get the index file downloaded and I get this warning in the console:

```
[warn] - play.core.server.netty.NettyModelConversion - Content-Type set both in header (text/html; charset=utf-8) and attached to entity (text/html; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content
 type, rather than setting the header manually.

```

To make it run as "Prod" under windows you need to add the following to Build.sbt:

`lazy val root = (project in file(".")).enablePlugins(PlayJava, LauncherJarPlugin)
`
If Linux you can skip adding "LauncherJarPlugin".

Then use activator: 
(if first time run this first `.\activator playUpdateSecret`)
Then:
`activator clean compile start`

Try now `http://localhost:9000/ui/`

I can reproduce this with the project : https://github.com/mmizutani/play-java-with-sbt-gulp 

And issue in Windows 10 and Linux (CentOS and Fedora to be specific).

**Comment by miguelCT** [comment]
It seems to be a Play! bug in 2.5.2 version, take a look to [this issue](https://groups.google.com/forum/#!topic/play-framework/Of0-DsW6r3Y). With 2.5.1 works fine.

**Comment by almothafar** [comment]
@miguelCT thanks you, yes seems that right, i downgraded to 2.5.1 and this solved the problem.

**Comment by mmizutani** [comment]
Play 2.5.3 with the fix for the issue above is out. https://github.com/playframework/playframework/pull/6058
Use this plugin with sbt-play 2.5.3.
