### ISSUE TITLE
Gulp container does not integrate with sbt docker publish

### ISSUE THREAD

**Issue by mavarazy** [mmizutani/sbt-play-gulp#2]
I'm trying sbt-play-gulp, in my project.
When calling docker:stage & docker:publishLocal, I expect to have image with appropriate ui, but I get 404 on /ui requests instead.

**Comment by mmizutani** [comment]
Sorry. There was [a bug](https://github.com/mmizutani/sbt-play-gulp/pull/1) in v0.0.4.
Please use the latest version 0.0.5.

**Comment by mavarazy** [comment]
I thought I took the latest one :)
Thanks :)
