### ISSUE TITLE
Readme instructions don't work with the samples

### ISSUE THREAD

**Issue by jeantil** [mmizutani/sbt-play-gulp#20]
More specifically the part 9 of [How to use this sbt plugin](https://github.com/mmizutani/sbt-play-gulp#how-to-use-this-sbt-plugin) says 

>Edit package.json, bower.json and gulpfile.js, enter the play-sbt console, and install public libraries:
```
$ sbt (or activator)
[your-play-project] $ npm install
[your-play-project] $ bower install
```

I cloned the repo , went into the `play-gulp-angular` sample, booted sbt and tried to run both commands here is the output I get. 
```
[play-gulp-angular] $ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/jean/dev/src/sbt-play-gulp/samples/play-gulp-angular/package.json'
npm WARN play-gulp-angular No description
npm WARN play-gulp-angular No repository field.
npm WARN play-gulp-angular No README data
npm WARN play-gulp-angular No license field.
```
```
play-gulp-angular] $ bower install
(node:57524) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
bower                           ENOENT No bower.json present
```
I have the same results with the `play-gulp-react` sample.

It looks like the commands are not chdir() to the `ui` subdirectory before being run. Is it an error of the README which should read instead :
```
your-play-project $> cd ui
your-play-project/ui $> npm install
your-play-project/ui $> bower install
your-play-project/ui $> cd ..
```

**Comment by mmizutani** [comment]
Yes. You are right. Thank you for the heads up.
