### ISSUE TITLE
create version for play 2.6.0-M1 / scala 2.12

### ISSUE THREAD

**Issue by domdorn** [mmizutani/sbt-play-gulp#27]

**Comment by almothafar** [comment]
the final release still not out.

**Comment by domdorn** [comment]
@almothafar yes, still you want this to be ready before the release is out, or this plugin will block people from upgrading. 
At the moment 2.6.0-M1 is out and this plugin is blocking me from upgrading.

**Comment by venkatzifo** [comment]
When the release of this plugin is expected for Play 2.6 version. It stops me from upgrading to latest version of play.

**Comment by almothafar** [comment]
@mmizutani any chance to see this issue, it is 2.6.7 right now

**Comment by udalrich** [comment]
The last commit was in late 2016.  We may need to either find a replacement project or have someone fork it.

**Comment by almothafar** [comment]
@udalrich author still active so if you pull request I think he might accept it and merge it, I would do it if I knew scala.

**Comment by mmizutani** [comment]
v0.2.0 with support for Play 2.6 and Scala 2.12 is out.
