### ISSUE TITLE
error: `<+=` operator is removed. Try `lhs += { x.value }`

### ISSUE THREAD

**Issue by joseblas** [mmizutani/sbt-play-gulp#30]
error: `<+=` operator is removed. Try `lhs += { x.value }`

unmanagedResourceDirectories in Assets <+= (gulpDirectory in Compile)(base => base / "build")
sbt 1.1.1
sbt.version=1.1.1

Play 2.6.11
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.11")

addSbtPlugin("com.github.mmizutani" % "sbt-play-gulp" % "0.2.0")

------
When creating a new Play project I get this error.

**Comment by mmizutani** [comment]
The plugin and sample already migrated the operators to the new syntax, but I forgot to update that part of the doc. The README has just been fixed: https://github.com/mmizutani/sbt-play-gulp/commit/92c652b7fe980dd6717efbf00f78a10d15b1399d. Thanks.

**Comment by joseblas** [comment]
Hi,
 sorry to bother you, but the documentation is not updated.

`import PlayGulpKeys._` fails 
and this is mentioned twice:
`import com.github.mmizutani.sbt.gulp.PlayGulpPlugin`
`import PlayGulpPlugin._`

 And still getting an exception when:
`unmanagedResourceDirectories in Assets += (gulpDirectory in Compile)(base => base / "app/dist")`
what makes my assets jar not to have the assets.

 Thanks, for this lib. I've used before and is great.

**Comment by joseblas** [comment]
this works `unmanagedResourceDirectories in Assets += baseDirectory.value / "pictures"`

**Comment by mmizutani** [comment]
This also work:
https://github.com/mmizutani/sbt-play-gulp/blob/92c652b7fe980dd6717efbf00f78a10d15b1399d/sbt-play-gulp/src/main/scala/com/github/mmizutani/sbt/gulp/PlayGulpPlugin.scala#L101-L102
