### ISSUE TITLE
Compilation Error in 0.1.0 version (Play 2.5)

### ISSUE THREAD

**Issue by miguelCT** [mmizutani/sbt-play-gulp#9]
I've been trying to use the 0.1.0 version of the plugin in my Play 2.5 project, but it seems something is wrong in the last version.

Play throws the next compilation error when trying to access to the Gulp class in the Routes file:
##### Routes

```
GET     /ui     com.github.mmizutani.playgulp.Gulp.index
```
##### Compilation Error

``` scala
type Gulp is not a member of package com.github.mmizutani.playgulp
```

Besides, I tried to run the **play-gulp-sample** but I got the same compilation error in the Routes file, so I suppose I'm not doing anything wrong in my project configuration.

> Note: I got another error in the sample project when trying to get **demo.scala.html**  in  **Application controller** (`Ok(views.html.demo(...)`). Maybe it's related to the same issue.

**Comment by mmizutani** [comment]
Please use the version 0.1.1 and change

```
GET        /ui      com.github.mmizutani.playgulp.Gulp.index
```

to

```
GET        /ui      com.github.mmizutani.playgulp.GulpAssets.index
```

**Comment by almothafar** [comment]
+1
I got 
`type GulpAssetes is not a member of package com.github.mmizutani.playgulp`

I'm using PlayJava btw.

**Comment by mmizutani** [comment]
@almothafar
Do you see the same error even after you import the version 0.1.1, not 0.1.0, of this plugin and run `sbt clean update`? [This plain Play-Java app with the sbt-play-gulp plugin](https://github.com/mmizutani/play-java-with-sbt-gulp) works fine.

**Comment by almothafar** [comment]
@mmizutani yes I did and was not helping me, but thanks for example, and btw its the same of my project structure, the problems seems make no sense maybe from wrong configuration, what I tried now and made it works:
- Removed the imports from `build.sbt` (its like what you have explaining in README ); `import com.github.mmizutani.sbt.gulp.PlayGulpPlugin` and `PlayGulpPlugin.playGulpSettings ++ PlayGulpPlugin.withTemplates` 
- Cleared the target folders manually 
- And I ran `activator clean update stage` before run the play for debug

Still not really trust with everything will be still stable, I got big number of issues every-time I try to run play, like sometimes I was unable to live reload the page, but now I can make changes -> refresh -> I see changes while before 30 minutes I was unable to do that without restart the activator, (i'm not sure, still if everything is OK in this part, like browser sync now working for me now).

I hope its will stay working now.
